#
# 宏定义, 包含多个头文件目录, TRAVERSE_INCLUDE(name1 name2 ...)
#
MACRO(TRAVERSE_INCLUDE)

	FOREACH(param ${ARGN})

		INCLUDE_DIRECTORIES(${param})

	ENDFOREACH()

ENDMACRO(TRAVERSE_INCLUDE)


#
# 宏定义, 根据项目名包含多个头文件目录, TRAVERSE_INCLUDE_FOR_PROGRAM_NAME(name1 name2 ...)
#
MACRO(TRAVERSE_INCLUDE_FOR_PROGRAM_NAME)

	FOREACH(param ${ARGN})

		TARGET_INCLUDE_DIRECTORIES(${PROGRAM_NAME}	PUBLIC	${param})

	ENDFOREACH()

ENDMACRO(TRAVERSE_INCLUDE_FOR_PROGRAM_NAME)


#
# 宏定义, 包含多个头文件目录以及链接库文件, TRAVERSE_INCLUDE_AND_LIBRARIES(name1 name2 ...)
#
MACRO(TRAVERSE_INCLUDE_AND_LIBRARIES)

	FOREACH(param ${ARGN})

		INCLUDE_DIRECTORIES(${PROJECT_SOURCE_DIR}/${param})

		TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${param})

	ENDFOREACH()

ENDMACRO(TRAVERSE_INCLUDE_AND_LIBRARIES)
