#
# 宏定义, 遍历指定目录获取源文件, TRAVERSE_LIBRARY(arg, path, type)
#
MACRO(TRAVERSE_LIBRARY)

	IF(NOT ${ARGC} LESS 4)

		MESSAGE(FATAL_ERROR "ARGC NUMBER ERROR")

	ENDIF()

	FILE(GLOB_RECURSE ${ARGV0}	"${ARGV1}/*${ARGV2}")

	FOREACH(file ${${ARGV0}})

		MESSAGE(STATUS "Found " ${PROGRAM_NAME} " Libraries : " ${file})

	ENDFOREACH()

ENDMACRO(TRAVERSE_LIBRARY)


#
# 宏定义, 遍历当前目录获取源文件, TRAVERSE_CURRENT_LIBRARY(arg, type)
#
MACRO(TRAVERSE_CURRENT_LIBRARY)

	IF(NOT ${ARGC} LESS 3)

		MESSAGE(FATAL_ERROR "ARGC NUMBER ERROR")

	ENDIF()

	FILE(GLOB_RECURSE ${ARGV0}	"*${ARGV1}")

	FOREACH(file ${${ARGV0}})

		MESSAGE(STATUS "Found " ${PROGRAM_NAME} " Libraries : " ${file})

	ENDFOREACH()

ENDMACRO(TRAVERSE_CURRENT_LIBRARY)