#
# 设置包名
#
SET(PROGRAM_NAME OpenSSL)


#
# 设置路径
#
SET(OPENSSL_SOFTWARE_PATH /home/software/openssl/openssl-1.1.0g)


#
# 检查路径
#
IF (IS_DIRECTORY ${OPENSSL_SOFTWARE_PATH})

	#
	# 输出信息
	#
	MESSAGE(STATUS "Found " ${PROGRAM_NAME} " Directory : " ${OPENSSL_SOFTWARE_PATH})

	#
	# 设置路径
	#
	SET(OPENSSL_SOFTWARE_LIBRARY_PATH		${OPENSSL_SOFTWARE_PATH}/lib)
	SET(OPENSSL_SOFTWARE_INCLUDE_PATH		${OPENSSL_SOFTWARE_PATH}/include)

ELSE()

	#
	# 输出信息
	#
	MESSAGE(FATAL_ERROR "Not Found " ${PROGRAM_NAME} " Directory : " ${OPENSSL_SOFTWARE_PATH})

ENDIF()
