#
# 设置包名
#
SET(PROGRAM_NAME GperfTools)


#
# 设置路径
#
SET(GPERF_TOOLS_SOFTWARE_PATH /home/software/gperftools/gperftools)


#
# 检查路径
#
IF (IS_DIRECTORY ${GPERF_TOOLS_SOFTWARE_PATH})

	#
	# 输出信息
	#
	MESSAGE(STATUS "Found " ${PROGRAM_NAME} " Directory : " ${GPERF_TOOLS_SOFTWARE_PATH})

	#
	# 设置路径
	#
	SET(GPERF_TOOLS_SOFTWARE_LIBRARY_PATH		${GPERF_TOOLS_SOFTWARE_PATH}/lib)
	SET(GPERF_TOOLS_SOFTWARE_INCLUDE_PATH		${GPERF_TOOLS_SOFTWARE_PATH}/include)

ELSE()

	#
	# 输出信息
	#
	MESSAGE(FATAL_ERROR "Not Found " ${PROGRAM_NAME} " Directory : " ${GPERF_TOOLS_SOFTWARE_PATH})

ENDIF()
