#
# 设置包名
#
SET(PROGRAM_NAME Libmemcached)


#
# 设置路径
#
SET(LIBMEMCACHED_SOFTWARE_PATH /home/software/memcached/libmemcached-1.0.18)


#
# 检查路径
#
IF (IS_DIRECTORY ${LIBMEMCACHED_SOFTWARE_PATH})

	#
	# 输出信息
	#
	MESSAGE(STATUS "Found " ${PROGRAM_NAME} " Directory : " ${LIBMEMCACHED_SOFTWARE_PATH})

	#
	# 设置路径
	#
	SET(LIBMEMCACHED_SOFTWARE_LIBRARY_PATH		${LIBMEMCACHED_SOFTWARE_PATH}/lib)
	SET(LIBMEMCACHED_SOFTWARE_INCLUDE_PATH		${LIBMEMCACHED_SOFTWARE_PATH}/include)

ELSE()

	#
	# 输出信息
	#
	MESSAGE(FATAL_ERROR "Not Found " ${PROGRAM_NAME} " Directory : " ${LIBMEMCACHED_SOFTWARE_PATH})

ENDIF()
